import { chromium, BrowserContext, Page, Locator } from 'playwright';
import axios from 'axios';
import * as dotenv from 'dotenv';
dotenv.config();

const FASTAPI_URL=process.env.FASTAPI_URL||'http://localhost:8000';
const AUTH=process.env.TWITTER_AUTH_TOKEN||'';
const CT0=process.env.TWITTER_CT0||'';
const HANDLE=process.env.XOSHI_HANDLE||'xoshi_Si';
const QUERIES=['$XOSHI','"Stock Tokens"','"tokenized stocks"','"Robinhood Chain"','"RWA" "AI agents"','DeFi "AI agents"','"onchain finance" "AI agents"'];
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));

async function clearOverlays(page:Page){try{await page.keyboard.press('Escape');await sleep(300);}catch{} try{const ds=page.locator('[role="dialog"]');for(let i=await ds.count()-1;i>=0;i--){const d=ds.nth(i);if(!await d.isVisible().catch(()=>false))continue;const box=(await d.locator('[role="textbox"]').count())+(await d.locator('[contenteditable="true"]').count());if(box)continue;const c=d.locator('[aria-label="Close"],button[aria-label="Close"]').first();if(await c.count())await c.click({force:true,timeout:1000}).catch(()=>{});}}catch{}}
async function safeClick(l:Locator,page:Page,name:string){try{await l.scrollIntoViewIfNeeded({timeout:3000}).catch(()=>{});await l.click({timeout:5000});return true}catch(e){console.log(`Normal click failed for ${name}:`,e instanceof Error?e.message:String(e));try{await l.click({force:true,timeout:5000});console.log(`Force click succeeded for ${name}.`);return true}catch{try{await l.evaluate((x:HTMLElement)=>x.click());console.log(`DOM click succeeded for ${name}.`);return true}catch{return false}}}}
async function health(){try{const r=await axios.get(`${FASTAPI_URL}/health`,{timeout:15000});console.log(`Backend alive: ${JSON.stringify(r.data)}`);return true}catch(e){console.log('Backend health failed:',e instanceof Error?e.message:String(e));return false}}
function lang(t:string){const s=` ${t.toLowerCase()} `;const p:Record<string,string[]>={es:[' que ',' los ',' las ',' una ',' para ',' opinión '],fr:[' les ',' des ',' une ',' pour ',' avec '],de:[' der ',' die ',' das ',' und ',' für '],it:[' gli ',' una ',' per ',' con '],pt:[' os ',' as ',' uma ',' para ',' com '],ca:[' els ',' les ',' una ',' per ',' amb '],en:[' the ',' what ',' how ',' stocks ',' tokens ']};let b='en',bs=0;for(const [k,v] of Object.entries(p)){const n=v.filter(x=>s.includes(x)).length;if(n>bs){b=k;bs=n}}return b}
async function context():Promise<BrowserContext>{if(!AUTH||!CT0)throw new Error('Missing Twitter credentials');const b=await chromium.launch({headless:true,args:['--no-sandbox','--disable-setuid-sandbox','--disable-dev-shm-usage']});const c=await b.newContext({viewport:{width:1440,height:1000},locale:'en-US',timezoneId:'Europe/Madrid'});await c.addCookies([{name:'auth_token',value:AUTH,domain:'.x.com',path:'/',httpOnly:true,secure:true,sameSite:'Lax'},{name:'ct0',value:CT0,domain:'.x.com',path:'/',httpOnly:false,secure:true,sameSite:'Lax'}]);return c}
async function session(p:Page){await p.goto('https://x.com/home',{waitUntil:'domcontentloaded',timeout:30000});await sleep(4000);const login=p.locator('a[href="/login"],a[href="/i/flow/login"]').first();if(await login.count()&&await login.isVisible().catch(()=>false))return false;console.log(`X session valid: @${HANDLE}`);return true}
async function extract(p:Page){const out:any[]=[];const as=p.locator('article[data-testid="tweet"]');for(let i=0;i<await as.count();i++){try{const a=as.nth(i);const text=(await a.locator('[data-testid="tweetText"]').allTextContents()).join(' ').trim();if(!text)continue;let id='';const ls=a.locator('a[href*="/status/"]');for(let j=0;j<await ls.count();j++){const h=await ls.nth(j).getAttribute('href');const m=h?.match(/\/status\/(\d+)/);if(m){id=m[1];break}}if(!id)continue;let author='';const us=a.locator('a[href^="/"][role="link"]');for(let j=0;j<await us.count();j++){const h=await us.nth(j).getAttribute('href');if(h&&h.startsWith('/')&&!h.includes('/status/')){author=h.replace('/','').split('/')[0];if(author)break}}out.push({id,text,author})}catch{}}return out}
async function candidates(p:Page){try{await p.goto(`https://x.com/${HANDLE}/with_replies`,{waitUntil:'domcontentloaded',timeout:30000});await sleep(4000);const t=await extract(p);const m=t.filter(x=>x.text.toLowerCase().includes(`@${HANDLE.toLowerCase()}`));console.log(`Mention candidates: ${m.length}`);return m}catch(e){console.log('Mention scan failed:',e instanceof Error?e.message:String(e));return[]}}
async function ai(tweet:string,author:string,task='reply',query=''){try{const r=await axios.post(`${FASTAPI_URL}/api/reading/reply`,{handle:HANDLE,author,tweet,language:lang(tweet),task,query},{timeout:30000});return String(r.data?.reply||r.data?.text||'').trim()}catch(e){console.log('AI generation failed:',e instanceof Error?e.message:String(e));return ''}}
async function reply(p:Page,t:any,text:string){try{console.log(`Opening tweet ${t.id}...`);await p.goto(`https://x.com/i/web/status/${t.id}`,{waitUntil:'domcontentloaded',timeout:30000});await sleep(4000);const a=p.locator('article[data-testid="tweet"]').first();const rb=a.locator('[data-testid="reply"],button[aria-label*="Reply"],div[role="button"][aria-label*="Reply"]').first();if(!await rb.count())return false;if(!await safeClick(rb,p,'reply button'))return false;await sleep(1200);const box=p.locator('[data-testid="tweetTextarea_0"],div[role="textbox"][contenteditable="true"],div[contenteditable="true"]').last();await box.waitFor({state:'visible',timeout:5000});await box.click({force:true});await p.keyboard.insertText(text);await sleep(700);const sb=p.locator('[data-testid="tweetButtonInline"],[data-testid="tweetButton"]').last();if(await sb.count()&&await sb.isVisible().catch(()=>false)){if(!await safeClick(sb,p,'reply send button'))await p.keyboard.press('Control+Enter').catch(()=>{})}else await p.keyboard.press('Control+Enter').catch(()=>{});await sleep(1800);console.log('Reply sent.');return true}catch(e){console.log('postReply error:',e instanceof Error?e.message:String(e));return false}}
async function search(p:Page,q:string){try{console.log(`Search: ${q}`);await p.goto(`https://x.com/search?q=${encodeURIComponent(q)}&src=typed_query&f=live`,{waitUntil:'domcontentloaded',timeout:30000});await sleep(4000);const t=await extract(p);console.log(`   ${q} -> ${t.length} tweets extracted`);return t.map(x=>({...x,query:q}))}catch(e){console.log(`Search failed:`,e instanceof Error?e.message:String(e));return[]}}
async function post(p:Page,text:string){try{console.log('Creating X post...');await p.goto('https://x.com/compose/post',{waitUntil:'domcontentloaded',timeout:30000});await sleep(5000);console.log(`Current URL: ${p.url()}`);const box=p.locator('[data-testid="tweetTextarea_0"],div[role="textbox"][contenteditable="true"],div[contenteditable="true"]').first();await box.waitFor({state:'visible',timeout:8000});await box.click({force:true});await p.keyboard.insertText(text);await sleep(1000);const sb=p.locator('[data-testid="tweetButton"],[data-testid="tweetButtonInline"]').last();if(await sb.count()&&await sb.isVisible().catch(()=>false)){if(!await safeClick(sb,p,'post button'))await p.keyboard.press('Control+Enter').catch(()=>{})}else await p.keyboard.press('Control+Enter').catch(()=>{});await sleep(2500);console.log('Post sent.');return true}catch(e){console.log('Post composer failed:',e instanceof Error?e.message:String(e));console.log(`Current URL: ${p.url()}`);console.log(`Textbox count: ${await p.locator('[role="textbox"]').count().catch(()=>0)}`);console.log(`Contenteditable count: ${await p.locator('[contenteditable="true"]').count().catch(()=>0)}`);return false}}
async function main(){console.log('========== XOSHI XI / SIBILI-STYLE CYCLE ==========');await health();let c:BrowserContext|null=null;try{c=await context();const p=c.pages()[0]||await c.newPage();if(!await session(p))throw new Error('X authentication invalid');console.log('--- DIRECT MENTIONS ---');const ms=await candidates(p);let mr=0;for(const t of ms){if(t.author?.toLowerCase()===HANDLE.toLowerCase())continue;console.log(`Mention @${t.author}: ${t.text}`);const r=await ai(t.text,t.author||'');if(r&&await reply(p,t,r))mr++;await sleep(1500)}console.log(`Mention replies: ${mr}`);console.log('--- MARKET / CRYPTO RADAR ---');let radar:any[]=[];for(const q of QUERIES){radar.push(...await search(p,q));await sleep(800)}let rr=0;for(const t of radar.slice(0,3)){if(t.author?.toLowerCase()===HANDLE.toLowerCase())continue;const r=await ai(t.text,t.author||'','radar_reply',t.query);if(r&&await reply(p,t,r))rr++;await sleep(1500)}console.log(`Radar replies: ${rr}`);if(mr===0&&rr===0)await post(p,'The interesting part of tokenization isn’t putting assets onchain.\n\nIt’s what happens when ownership becomes programmable.\n\n$XOSHI');else console.log('Skipping autonomous post because the cycle already generated engagement.');console.log('Cycle complete.')}finally{if(c)await c.close().catch(()=>{})}}
main().catch(e=>{console.error('Fatal Xoshi XI error:',e instanceof Error?e.stack||e.message:String(e));process.exit(1)})
