import { chromium, BrowserContext, Page } from 'playwright';
import axios from 'axios';
import fs from 'fs';
import path from 'path';
const FASTAPI_URL=(process.env.FASTAPI_URL||'').replace(/\/$/,'');
const HANDLE=process.env.XOSHI_HANDLE||'xoshi_Si';
const PROFILE=process.env.XOSHI_PROFILE_DIR||path.join(process.cwd(),'profiles','xoshi-main');
const AUTH=process.env.TWITTER_AUTH_TOKEN, CT0=process.env.TWITTER_CT0;
function lang(t:string){if(/[¿¡]|\b(el|la|los|las|que|para|como|hola)\b/i.test(t))return'es';if(/\b(le|les|avec|pour|bonjour)\b/i.test(t))return'fr';if(/\b(der|die|das|und|nicht)\b/i.test(t))return'de';if(/\b(para|você|não|uma)\b/i.test(t))return'pt';if(/\b(per|che|una|come)\b/i.test(t))return'it';return'en'}
async function setup():Promise<BrowserContext>{const ctx=await chromium.launchPersistentContext(PROFILE,{headless:true}); if(AUTH&&CT0) await ctx.addCookies([{name:'auth_token',value:AUTH,domain:'.x.com',path:'/'},{name:'ct0',value:CT0,domain:'.x.com',path:'/'}]); return ctx;}
async function search(page:Page,q:string){await page.goto('https://x.com/search?q='+encodeURIComponent(q)+'&src=typed_query&f=live',{waitUntil:'domcontentloaded',timeout:45000}); await page.waitForTimeout(2500); return await page.locator('article').evaluateAll(es=>es.map(e=>({text:(e.textContent||'').trim(),link:(e.querySelector('a[href*="/status/"]') as HTMLAnchorElement)?.href||''})).slice(0,10));}
async function reply(page:Page,link:string,text:string){await page.goto(link,{waitUntil:'domcontentloaded',timeout:45000});await page.waitForTimeout(1500);const btn=page.getByRole('button',{name:/Reply|Responder/i}).first();await btn.click();await page.waitForTimeout(500);const box=page.locator('textarea').first();await box.fill(text.slice(0,270));await page.getByTestId('tweetButton').click();}
async function post(page:Page,text:string){await page.goto('https://x.com/compose/post',{waitUntil:'domcontentloaded'});await page.waitForTimeout(1000);const box=page.locator('[data-testid="tweetTextarea_0"]').first();await box.fill(text.slice(0,270));await page.getByTestId('tweetButton').click();}
async function main(){if(!FASTAPI_URL)throw new Error('FASTAPI_URL missing');const ctx=await setup();const page=await ctx.newPage();try{const mentions=await search(page,`@${HANDLE}`);let count=0;for(const m of mentions){if(!m.link)continue;const a=await axios.post(`${FASTAPI_URL}/api/intelligence/mention`,{author:'unknown',text:m.text,detected_language:lang(m.text)});await reply(page,m.link,a.data.reply);if(++count>=5)break;}const queries=['$XOSHI','"Stock Tokens"','"tokenized stocks"','"Robinhood Chain"','RWA "AI agents"'];let replies=0;for(const q of queries){if(replies>=2)break;const items=await search(page,q);for(const it of items){if(!it.link)continue;const a=await axios.post(`${FASTAPI_URL}/api/intelligence/analyze`,{author:'unknown',text:it.text,detected_language:lang(it.text),preferred:'gemini'});if(a.data.decision==='REPLY'&&Number(a.data.confidence)>=0.68){await reply(page,it.link,a.data.reply);replies++;break;}}} }finally{await ctx.close();}}
main().catch(e=>{console.error(e);process.exit(1)});
